# this workflow will run on every pr to make sure the project is following the guidelines

# after labeler, run other actions with strict permissions
name: CI

on:
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: yarn.lock
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    name: Run Prettier
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: yarn.lock
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn format:check

  tsc:
    runs-on: ubuntu-latest
    name: Run Typechecker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: yarn.lock
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn typecheck

  build:
    runs-on: ubuntu-latest
    name: Build and Check Astro
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: yarn.lock
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn build
        # env:
        #   PUBLIC_GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
